// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// BackendAuthenticationConfig message groups the TrustConfig together with
/// other settings that control how the load balancer authenticates, and
/// expresses its identity to, the backend:
///
/// * `trustConfig` is the attached TrustConfig.
///
/// * `wellKnownRoots` indicates whether the load balance should trust backend
/// server certificates that are issued by public certificate authorities, in
/// addition to certificates trusted by the TrustConfig.
///
/// * `clientCertificate` is a client certificate that the load balancer uses to
/// express its identity to the backend, if the connection to the backend uses
/// mTLS.
///
/// You can attach the BackendAuthenticationConfig to the load balancer's
/// BackendService directly determining how that BackendService negotiates TLS.
public struct BackendAuthenticationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the BackendAuthenticationConfig resource. It matches the
  /// pattern
  /// `projects/*/locations/{location}/backendAuthenticationConfigs/{backend_authentication_config}`
  public var name: Swift.String = Swift.String()

  /// Optional. Free-text description of the resource.
  public var description: Swift.String = Swift.String()

  /// Output only. The timestamp when the resource was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp when the resource was updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Set of label tags associated with the resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A reference to a certificatemanager.googleapis.com.Certificate
  /// resource. This is a relative resource path following the form
  /// "projects/{project}/locations/{location}/certificates/{certificate}".
  ///
  /// Used by a BackendService to negotiate mTLS when the backend connection uses
  /// TLS and the backend requests a client certificate. Must have a CLIENT_AUTH
  /// scope.
  public var clientCertificate: Swift.String = Swift.String()

  /// Optional. A reference to a TrustConfig resource from the
  /// certificatemanager.googleapis.com namespace. This is a relative resource
  /// path following the form
  /// "projects/{project}/locations/{location}/trustConfigs/{trust_config}".
  ///
  /// A BackendService uses the chain of trust represented by this TrustConfig,
  /// if specified, to validate the server certificates presented by the backend.
  /// Required unless wellKnownRoots is set to PUBLIC_ROOTS.
  public var trustConfig: Swift.String = Swift.String()

  /// Well known roots to use for server certificate validation.
  public var wellKnownRoots: BackendAuthenticationConfig.WellKnownRoots =
    BackendAuthenticationConfig.WellKnownRoots()

  /// Output only. Etag of the resource.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `BackendAuthenticationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackendAuthenticationConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enum to specify the well known roots to use for server certificate
  /// validation.
  public enum WellKnownRoots: Codable, Equatable, Sendable {
    /// Equivalent to NONE.
    case unspecified
    /// The BackendService will only validate server certificates against roots
    /// specified in TrustConfig.
    case `none`
    /// The BackendService uses a set of well-known public roots, in addition to
    /// any roots specified in the trustConfig field, when validating the server
    /// certificates presented by the backend. Validation with these roots is
    /// only considered when the TlsSettings.sni field in the BackendService is
    /// set.
    ///
    /// The well-known roots are a set of root CAs managed by Google. CAs in this
    /// set can be added or removed without notice.
    case publicRoots
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .publicRoots: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "WELL_KNOWN_ROOTS_UNSPECIFIED"
      case .`none`: return "NONE"
      case .publicRoots: return "PUBLIC_ROOTS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:WellKnownRoots/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "WELL_KNOWN_ROOTS_UNSPECIFIED": self = .unspecified
      case "NONE": self = .`none`
      case "PUBLIC_ROOTS": self = .publicRoots
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:WellKnownRoots/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .publicRoots
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`none`: return try container.encode(1)
      case .publicRoots: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networksecurity.v1.BackendAuthenticationConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
