// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// ClientTlsPolicy is a resource that specifies how a client should authenticate
/// connections to backends of a service. This resource itself does not affect
/// configuration unless it is attached to a backend service resource.
public struct ClientTlsPolicy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Name of the ClientTlsPolicy resource. It matches the pattern
  /// `projects/{project}/locations/{location}/clientTlsPolicies/{client_tls_policy}`
  public var name: Swift.String = Swift.String()

  /// Optional. Free-text description of the resource.
  public var description: Swift.String = Swift.String()

  /// Output only. The timestamp when the resource was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The timestamp when the resource was updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Set of label tags associated with the resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Server Name Indication string to present to the server during TLS
  /// handshake. E.g: "secure.example.com".
  public var sni: Swift.String = Swift.String()

  /// Optional. Defines a mechanism to provision client identity (public and
  /// private keys) for peer to peer authentication. The presence of this
  /// dictates mTLS.
  public var clientCertificate: CertificateProvider? = nil

  /// Optional. Defines the mechanism to obtain the Certificate Authority
  /// certificate to validate the server certificate. If empty, client does not
  /// validate the server certificate.
  public var serverValidationCa: [ValidationCA] = []

  /// Initialize a new instance of `ClientTlsPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClientTlsPolicy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networksecurity.v1.ClientTlsPolicy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
