// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ClientTlsPolicy is a resource that specifies how a client should authenticate
/// connections to backends of a service. This resource itself does not affect
/// configuration unless it is attached to a backend service resource.
public struct ClientTlsPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Name of the ClientTlsPolicy resource. It matches the pattern
  /// `projects/{project}/locations/{location}/clientTlsPolicies/{client_tls_policy}`
  public var name: Swift.String = Swift.String()

  /// Optional. Free-text description of the resource.
  public var description: Swift.String = Swift.String()

  /// Output only. The timestamp when the resource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp when the resource was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Set of label tags associated with the resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Server Name Indication string to present to the server during TLS
  /// handshake. E.g: "secure.example.com".
  public var sni: Swift.String = Swift.String()

  /// Optional. Defines a mechanism to provision client identity (public and
  /// private keys) for peer to peer authentication. The presence of this
  /// dictates mTLS.
  public var clientCertificate: CertificateProvider? = nil

  /// Optional. Defines the mechanism to obtain the Certificate Authority
  /// certificate to validate the server certificate. If empty, client does not
  /// validate the server certificate.
  public var serverValidationCa: [ValidationCA] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ClientTlsPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClientTlsPolicy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let sni = CodingKeys(stringValue: "sni")
    static let clientCertificate = CodingKeys(stringValue: "clientCertificate")
    static let serverValidationCa = CodingKeys(stringValue: "serverValidationCa")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "createTime",
      "updateTime",
      "labels",
      "sni",
      "clientCertificate",
      "serverValidationCa",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sni) {
      self.sni = value
    }
    self.clientCertificate = try container.decodeIfPresent(
      CertificateProvider.self, forKey: .clientCertificate)
    if let value = try container.decodeIfPresent([ValidationCA].self, forKey: .serverValidationCa) {
      self.serverValidationCa = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.sni, forKey: .sni)
    try container.encodeIfPresent(self.clientCertificate, forKey: .clientCertificate)
    try container.encode(self.serverValidationCa, forKey: .serverValidationCa)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networksecurity.v1.ClientTlsPolicy"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
