// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The message to create a DnsThreatDetector.
public struct CreateDnsThreatDetectorRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The value for the parent of the DnsThreatDetector resource.
  public var parent: Swift.String = Swift.String()

  /// Optional. The ID of the requesting DnsThreatDetector object.
  /// If this field is not supplied, the service generates an identifier.
  public var dnsThreatDetectorId: Swift.String = Swift.String()

  /// Required. The `DnsThreatDetector` resource to create.
  public var dnsThreatDetector: DnsThreatDetector? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateDnsThreatDetectorRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateDnsThreatDetectorRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let dnsThreatDetectorId = CodingKeys(stringValue: "dnsThreatDetectorId")
    static let dnsThreatDetector = CodingKeys(stringValue: "dnsThreatDetector")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "dnsThreatDetectorId",
      "dnsThreatDetector",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dnsThreatDetectorId) {
      self.dnsThreatDetectorId = value
    }
    self.dnsThreatDetector = try container.decodeIfPresent(
      DnsThreatDetector.self, forKey: .dnsThreatDetector)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.dnsThreatDetectorId, forKey: .dnsThreatDetectorId)
    try container.encodeIfPresent(self.dnsThreatDetector, forKey: .dnsThreatDetector)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networksecurity.v1.CreateDnsThreatDetectorRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
