// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for CreateMirroringDeploymentGroup.
public struct CreateMirroringDeploymentGroupRequest: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Required. The parent resource where this deployment group will be created.
  /// Format: projects/{project}/locations/{location}
  public var parent: Swift.String = Swift.String()

  /// Required. The ID to use for the new deployment group, which will become the
  /// final component of the deployment group's resource name.
  public var mirroringDeploymentGroupId: Swift.String = Swift.String()

  /// Required. The deployment group to create.
  public var mirroringDeploymentGroup: MirroringDeploymentGroup? = nil

  /// Optional. A unique identifier for this request. Must be a UUID4.
  /// This request is only idempotent if a `request_id` is provided.
  /// See https://google.aip.dev/155 for more details.
  public var requestId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateMirroringDeploymentGroupRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateMirroringDeploymentGroupRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.networksecurity.v1.CreateMirroringDeploymentGroupRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
