// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A deployment represents a zonal intercept backend ready to accept
/// GENEVE-encapsulated traffic, e.g. a zonal instance group fronted by an
/// internal passthrough load balancer. Deployments are always part of a
/// global deployment group which represents a global intercept service.
public struct InterceptDeployment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Immutable. Identifier. The resource name of this deployment, for example:
  /// `projects/123456789/locations/us-central1-a/interceptDeployments/my-dep`.
  /// See https://google.aip.dev/122 for more details.
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp when the resource was created.
  /// See https://google.aip.dev/148#timestamps.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The timestamp when the resource was most recently updated.
  /// See https://google.aip.dev/148#timestamps.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Labels are key/value pairs that help to organize and filter
  /// resources.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. Immutable. The regional forwarding rule that fronts the
  /// interceptors, for example:
  /// `projects/123456789/regions/us-central1/forwardingRules/my-rule`.
  /// See https://google.aip.dev/124.
  public var forwardingRule: Swift.String = Swift.String()

  /// Required. Immutable. The deployment group that this deployment is a part
  /// of, for example:
  /// `projects/123456789/locations/global/interceptDeploymentGroups/my-dg`.
  /// See https://google.aip.dev/124.
  public var interceptDeploymentGroup: Swift.String = Swift.String()

  /// Output only. The current state of the deployment.
  /// See https://google.aip.dev/216.
  public var state: InterceptDeployment.State = InterceptDeployment.State()

  /// Output only. The current state of the resource does not match the user's
  /// intended state, and the system is working to reconcile them. This part of
  /// the normal operation (e.g. linking a new association to the parent group).
  /// See https://google.aip.dev/128.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. User-provided description of the deployment.
  /// Used as additional context for the deployment.
  public var description: Swift.String = Swift.String()

  /// Initialize a new instance of `InterceptDeployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InterceptDeployment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The current state of the deployment.
  public enum State: Codable, Equatable, Sendable {
    /// State not set (this is not a valid state).
    case unspecified
    /// The deployment is ready and in sync with the parent group.
    case active
    /// The deployment is being created.
    case creating
    /// The deployment is being deleted.
    case deleting
    /// The deployment is out of sync with the parent group.
    /// In most cases, this is a result of a transient issue within the system
    /// (e.g. a delayed data-path config) and the system is expected to recover
    /// automatically. See the parent deployment group's state for more details.
    case outOfSync
    /// An attempt to delete the deployment has failed. This is a terminal state
    /// and the deployment is not expected to recover. The only permitted
    /// operation is to retry deleting the deployment.
    case deleteFailed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .creating: return 2
      case .deleting: return 3
      case .outOfSync: return 4
      case .deleteFailed: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .outOfSync: return "OUT_OF_SYNC"
      case .deleteFailed: return "DELETE_FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "OUT_OF_SYNC": self = .outOfSync
      case "DELETE_FAILED": self = .deleteFailed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .creating
      case 3: self = .deleting
      case 4: self = .outOfSync
      case 5: self = .deleteFailed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .creating: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .outOfSync: return try container.encode(4)
      case .deleteFailed: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networksecurity.v1.InterceptDeployment"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
