// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  final class MirroringRetry: MirroringStub {
    let inner: any MirroringStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any MirroringStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listMirroringEndpointGroups(
      request: ListMirroringEndpointGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListMirroringEndpointGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMirroringEndpointGroupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListMirroringEndpointGroupsResponse
          in
          return try await self.inner.listMirroringEndpointGroups(request: r, options: o)
        })
    }

    public func getMirroringEndpointGroup(
      request: GetMirroringEndpointGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.MirroringEndpointGroup {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMirroringEndpointGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.MirroringEndpointGroup
          in
          return try await self.inner.getMirroringEndpointGroup(request: r, options: o)
        })
    }

    public func createMirroringEndpointGroup(
      request: CreateMirroringEndpointGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMirroringEndpointGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMirroringEndpointGroup(request: r, options: o)
        })
    }

    public func updateMirroringEndpointGroup(
      request: UpdateMirroringEndpointGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateMirroringEndpointGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMirroringEndpointGroup(request: r, options: o)
        })
    }

    public func deleteMirroringEndpointGroup(
      request: DeleteMirroringEndpointGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMirroringEndpointGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMirroringEndpointGroup(request: r, options: o)
        })
    }

    public func listMirroringEndpointGroupAssociations(
      request: ListMirroringEndpointGroupAssociationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListMirroringEndpointGroupAssociationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMirroringEndpointGroupAssociationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudNetworkSecurityV1.ListMirroringEndpointGroupAssociationsResponse
          in
          return try await self.inner.listMirroringEndpointGroupAssociations(request: r, options: o)
        })
    }

    public func getMirroringEndpointGroupAssociation(
      request: GetMirroringEndpointGroupAssociationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.MirroringEndpointGroupAssociation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMirroringEndpointGroupAssociationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudNetworkSecurityV1.MirroringEndpointGroupAssociation
          in
          return try await self.inner.getMirroringEndpointGroupAssociation(request: r, options: o)
        })
    }

    public func createMirroringEndpointGroupAssociation(
      request: CreateMirroringEndpointGroupAssociationRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMirroringEndpointGroupAssociationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMirroringEndpointGroupAssociation(
            request: r, options: o)
        })
    }

    public func updateMirroringEndpointGroupAssociation(
      request: UpdateMirroringEndpointGroupAssociationRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateMirroringEndpointGroupAssociationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMirroringEndpointGroupAssociation(
            request: r, options: o)
        })
    }

    public func deleteMirroringEndpointGroupAssociation(
      request: DeleteMirroringEndpointGroupAssociationRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMirroringEndpointGroupAssociationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMirroringEndpointGroupAssociation(
            request: r, options: o)
        })
    }

    public func listMirroringDeploymentGroups(
      request: ListMirroringDeploymentGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListMirroringDeploymentGroupsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMirroringDeploymentGroupsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListMirroringDeploymentGroupsResponse
          in
          return try await self.inner.listMirroringDeploymentGroups(request: r, options: o)
        })
    }

    public func getMirroringDeploymentGroup(
      request: GetMirroringDeploymentGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.MirroringDeploymentGroup {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMirroringDeploymentGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.MirroringDeploymentGroup
          in
          return try await self.inner.getMirroringDeploymentGroup(request: r, options: o)
        })
    }

    public func createMirroringDeploymentGroup(
      request: CreateMirroringDeploymentGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMirroringDeploymentGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMirroringDeploymentGroup(request: r, options: o)
        })
    }

    public func updateMirroringDeploymentGroup(
      request: UpdateMirroringDeploymentGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateMirroringDeploymentGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMirroringDeploymentGroup(request: r, options: o)
        })
    }

    public func deleteMirroringDeploymentGroup(
      request: DeleteMirroringDeploymentGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMirroringDeploymentGroupRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMirroringDeploymentGroup(request: r, options: o)
        })
    }

    public func listMirroringDeployments(
      request: ListMirroringDeploymentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListMirroringDeploymentsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListMirroringDeploymentsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListMirroringDeploymentsResponse
          in
          return try await self.inner.listMirroringDeployments(request: r, options: o)
        })
    }

    public func getMirroringDeployment(
      request: GetMirroringDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.MirroringDeployment {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetMirroringDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.MirroringDeployment
          in
          return try await self.inner.getMirroringDeployment(request: r, options: o)
        })
    }

    public func createMirroringDeployment(
      request: CreateMirroringDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateMirroringDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createMirroringDeployment(request: r, options: o)
        })
    }

    public func updateMirroringDeployment(
      request: UpdateMirroringDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateMirroringDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateMirroringDeployment(request: r, options: o)
        })
    }

    public func deleteMirroringDeployment(
      request: DeleteMirroringDeploymentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteMirroringDeploymentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteMirroringDeployment(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
