// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A deployment group aggregates many zonal mirroring backends (deployments)
/// into a single global mirroring service. Consumers can connect this service
/// using an endpoint group.
public struct MirroringDeploymentGroup: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. Identifier. The resource name of this deployment group, for
  /// example:
  /// `projects/123456789/locations/global/mirroringDeploymentGroups/my-dg`.
  /// See https://google.aip.dev/122 for more details.
  public var name: Swift.String = Swift.String()

  /// Output only. The timestamp when the resource was created.
  /// See https://google.aip.dev/148#timestamps.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The timestamp when the resource was most recently updated.
  /// See https://google.aip.dev/148#timestamps.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Labels are key/value pairs that help to organize and filter
  /// resources.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. Immutable. The network that will be used for all child
  /// deployments, for example: `projects/{project}/global/networks/{network}`.
  /// See https://google.aip.dev/124.
  public var network: Swift.String = Swift.String()

  /// Output only. The list of endpoint groups that are connected to this
  /// resource.
  public var connectedEndpointGroups: [MirroringDeploymentGroup.ConnectedEndpointGroup] = []

  /// Output only. The list of Mirroring Deployments that belong to this group.
  @available(*, deprecated)
  public var nestedDeployments: [MirroringDeploymentGroup.Deployment] = []

  /// Output only. The current state of the deployment group.
  /// See https://google.aip.dev/216.
  public var state: MirroringDeploymentGroup.State = MirroringDeploymentGroup.State()

  /// Output only. The current state of the resource does not match the user's
  /// intended state, and the system is working to reconcile them. This is part
  /// of the normal operation (e.g. adding a new deployment to the group) See
  /// https://google.aip.dev/128.
  public var reconciling: Swift.Bool = Swift.Bool()

  /// Optional. User-provided description of the deployment group.
  /// Used as additional context for the deployment group.
  public var description: Swift.String = Swift.String()

  /// Output only. The list of locations where the deployment group is present.
  public var locations: [MirroringLocation] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MirroringDeploymentGroup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MirroringDeploymentGroup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let network = CodingKeys(stringValue: "network")
    static let connectedEndpointGroups = CodingKeys(stringValue: "connectedEndpointGroups")
    static let nestedDeployments = CodingKeys(stringValue: "nestedDeployments")
    static let state = CodingKeys(stringValue: "state")
    static let reconciling = CodingKeys(stringValue: "reconciling")
    static let description = CodingKeys(stringValue: "description")
    static let locations = CodingKeys(stringValue: "locations")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "network",
      "connectedEndpointGroups",
      "nestedDeployments",
      "state",
      "reconciling",
      "description",
      "locations",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .network) {
      self.network = value
    }
    if let value = try container.decodeIfPresent(
      [MirroringDeploymentGroup.ConnectedEndpointGroup].self, forKey: .connectedEndpointGroups)
    {
      self.connectedEndpointGroups = value
    }
    if let value = try container.decodeIfPresent(
      [MirroringDeploymentGroup.Deployment].self, forKey: .nestedDeployments)
    {
      self.nestedDeployments = value
    }
    if let value = try container.decodeIfPresent(
      MirroringDeploymentGroup.State.self, forKey: .state)
    {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .reconciling) {
      self.reconciling = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([MirroringLocation].self, forKey: .locations) {
      self.locations = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.network, forKey: .network)
    try container.encode(self.connectedEndpointGroups, forKey: .connectedEndpointGroups)
    try container.encode(self.nestedDeployments, forKey: .nestedDeployments)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.reconciling, forKey: .reconciling)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.locations, forKey: .locations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// An endpoint group connected to this deployment group.
  public struct ConnectedEndpointGroup: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The connected endpoint group's resource name, for example:
    /// `projects/123456789/locations/global/mirroringEndpointGroups/my-eg`.
    /// See https://google.aip.dev/124.
    public var name: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConnectedEndpointGroup`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConnectedEndpointGroup().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")

      static let _knownKeys: Set<Swift.String> = [
        "name"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networksecurity.v1.MirroringDeploymentGroup.ConnectedEndpointGroup"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A deployment belonging to this deployment group.
  public struct Deployment: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The name of the Mirroring Deployment, in the format:
    /// `projects/{project}/locations/{location}/mirroringDeployments/{mirroring_deployment}`.
    public var name: Swift.String = Swift.String()

    /// Output only. Most recent known state of the deployment.
    public var state: MirroringDeployment.State = MirroringDeployment.State()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Deployment`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Deployment().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let state = CodingKeys(stringValue: "state")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "state",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(MirroringDeployment.State.self, forKey: .state) {
        self.state = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.state, forKey: .state)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.networksecurity.v1.MirroringDeploymentGroup.Deployment"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The current state of the deployment group.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// State not set (this is not a valid state).
    case unspecified
    /// The deployment group is ready.
    case active
    /// The deployment group is being created.
    case creating
    /// The deployment group is being deleted.
    case deleting
    /// The deployment group is being wiped out (project deleted).
    case closed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .creating: return 2
      case .deleting: return 3
      case .closed: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .closed: return "CLOSED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "CLOSED": self = .closed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .creating
      case 3: self = .deleting
      case 4: self = .closed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .creating: return try container.encode("CREATING")
      case .deleting: return try container.encode("DELETING")
      case .closed: return try container.encode("CLOSED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networksecurity.v1.MirroringDeploymentGroup"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
