// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class NetworkSecurityRetry: NetworkSecurityStub {
    let inner: any NetworkSecurityStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any NetworkSecurityStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listAuthorizationPolicies(
      request: ListAuthorizationPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListAuthorizationPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAuthorizationPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListAuthorizationPoliciesResponse
          in
          return try await self.inner.listAuthorizationPolicies(request: r, options: o)
        })
    }

    public func getAuthorizationPolicy(
      request: GetAuthorizationPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.AuthorizationPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAuthorizationPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.AuthorizationPolicy
          in
          return try await self.inner.getAuthorizationPolicy(request: r, options: o)
        })
    }

    public func createAuthorizationPolicy(
      request: CreateAuthorizationPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAuthorizationPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAuthorizationPolicy(request: r, options: o)
        })
    }

    public func updateAuthorizationPolicy(
      request: UpdateAuthorizationPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAuthorizationPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAuthorizationPolicy(request: r, options: o)
        })
    }

    public func deleteAuthorizationPolicy(
      request: DeleteAuthorizationPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAuthorizationPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAuthorizationPolicy(request: r, options: o)
        })
    }

    public func listBackendAuthenticationConfigs(
      request: ListBackendAuthenticationConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListBackendAuthenticationConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBackendAuthenticationConfigsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListBackendAuthenticationConfigsResponse
          in
          return try await self.inner.listBackendAuthenticationConfigs(request: r, options: o)
        })
    }

    public func getBackendAuthenticationConfig(
      request: GetBackendAuthenticationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.BackendAuthenticationConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBackendAuthenticationConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.BackendAuthenticationConfig
          in
          return try await self.inner.getBackendAuthenticationConfig(request: r, options: o)
        })
    }

    public func createBackendAuthenticationConfig(
      request: CreateBackendAuthenticationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBackendAuthenticationConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createBackendAuthenticationConfig(request: r, options: o)
        })
    }

    public func updateBackendAuthenticationConfig(
      request: UpdateBackendAuthenticationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBackendAuthenticationConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateBackendAuthenticationConfig(request: r, options: o)
        })
    }

    public func deleteBackendAuthenticationConfig(
      request: DeleteBackendAuthenticationConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteBackendAuthenticationConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteBackendAuthenticationConfig(request: r, options: o)
        })
    }

    public func listServerTlsPolicies(
      request: ListServerTlsPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListServerTlsPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListServerTlsPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListServerTlsPoliciesResponse
          in
          return try await self.inner.listServerTlsPolicies(request: r, options: o)
        })
    }

    public func getServerTlsPolicy(
      request: GetServerTlsPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ServerTlsPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetServerTlsPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ServerTlsPolicy
          in
          return try await self.inner.getServerTlsPolicy(request: r, options: o)
        })
    }

    public func createServerTlsPolicy(
      request: CreateServerTlsPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateServerTlsPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createServerTlsPolicy(request: r, options: o)
        })
    }

    public func updateServerTlsPolicy(
      request: UpdateServerTlsPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateServerTlsPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateServerTlsPolicy(request: r, options: o)
        })
    }

    public func deleteServerTlsPolicy(
      request: DeleteServerTlsPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteServerTlsPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteServerTlsPolicy(request: r, options: o)
        })
    }

    public func listClientTlsPolicies(
      request: ListClientTlsPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListClientTlsPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListClientTlsPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListClientTlsPoliciesResponse
          in
          return try await self.inner.listClientTlsPolicies(request: r, options: o)
        })
    }

    public func getClientTlsPolicy(
      request: GetClientTlsPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ClientTlsPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetClientTlsPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ClientTlsPolicy
          in
          return try await self.inner.getClientTlsPolicy(request: r, options: o)
        })
    }

    public func createClientTlsPolicy(
      request: CreateClientTlsPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateClientTlsPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createClientTlsPolicy(request: r, options: o)
        })
    }

    public func updateClientTlsPolicy(
      request: UpdateClientTlsPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateClientTlsPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateClientTlsPolicy(request: r, options: o)
        })
    }

    public func deleteClientTlsPolicy(
      request: DeleteClientTlsPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteClientTlsPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteClientTlsPolicy(request: r, options: o)
        })
    }

    public func listGatewaySecurityPolicies(
      request: ListGatewaySecurityPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListGatewaySecurityPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListGatewaySecurityPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListGatewaySecurityPoliciesResponse
          in
          return try await self.inner.listGatewaySecurityPolicies(request: r, options: o)
        })
    }

    public func getGatewaySecurityPolicy(
      request: GetGatewaySecurityPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.GatewaySecurityPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetGatewaySecurityPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.GatewaySecurityPolicy
          in
          return try await self.inner.getGatewaySecurityPolicy(request: r, options: o)
        })
    }

    public func createGatewaySecurityPolicy(
      request: CreateGatewaySecurityPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateGatewaySecurityPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGatewaySecurityPolicy(request: r, options: o)
        })
    }

    public func updateGatewaySecurityPolicy(
      request: UpdateGatewaySecurityPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateGatewaySecurityPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateGatewaySecurityPolicy(request: r, options: o)
        })
    }

    public func deleteGatewaySecurityPolicy(
      request: DeleteGatewaySecurityPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteGatewaySecurityPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGatewaySecurityPolicy(request: r, options: o)
        })
    }

    public func listGatewaySecurityPolicyRules(
      request: ListGatewaySecurityPolicyRulesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListGatewaySecurityPolicyRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListGatewaySecurityPolicyRulesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListGatewaySecurityPolicyRulesResponse
          in
          return try await self.inner.listGatewaySecurityPolicyRules(request: r, options: o)
        })
    }

    public func getGatewaySecurityPolicyRule(
      request: GetGatewaySecurityPolicyRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.GatewaySecurityPolicyRule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetGatewaySecurityPolicyRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.GatewaySecurityPolicyRule
          in
          return try await self.inner.getGatewaySecurityPolicyRule(request: r, options: o)
        })
    }

    public func createGatewaySecurityPolicyRule(
      request: CreateGatewaySecurityPolicyRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateGatewaySecurityPolicyRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createGatewaySecurityPolicyRule(request: r, options: o)
        })
    }

    public func updateGatewaySecurityPolicyRule(
      request: UpdateGatewaySecurityPolicyRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateGatewaySecurityPolicyRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateGatewaySecurityPolicyRule(request: r, options: o)
        })
    }

    public func deleteGatewaySecurityPolicyRule(
      request: DeleteGatewaySecurityPolicyRuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteGatewaySecurityPolicyRuleRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteGatewaySecurityPolicyRule(request: r, options: o)
        })
    }

    public func listUrlLists(
      request: ListUrlListsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListUrlListsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListUrlListsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListUrlListsResponse
          in
          return try await self.inner.listUrlLists(request: r, options: o)
        })
    }

    public func getUrlList(
      request: GetUrlListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.UrlList {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetUrlListRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.UrlList
          in
          return try await self.inner.getUrlList(request: r, options: o)
        })
    }

    public func createUrlList(
      request: CreateUrlListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateUrlListRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createUrlList(request: r, options: o)
        })
    }

    public func updateUrlList(
      request: UpdateUrlListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateUrlListRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateUrlList(request: r, options: o)
        })
    }

    public func deleteUrlList(
      request: DeleteUrlListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteUrlListRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteUrlList(request: r, options: o)
        })
    }

    public func listTlsInspectionPolicies(
      request: ListTlsInspectionPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListTlsInspectionPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTlsInspectionPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListTlsInspectionPoliciesResponse
          in
          return try await self.inner.listTlsInspectionPolicies(request: r, options: o)
        })
    }

    public func getTlsInspectionPolicy(
      request: GetTlsInspectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.TlsInspectionPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTlsInspectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.TlsInspectionPolicy
          in
          return try await self.inner.getTlsInspectionPolicy(request: r, options: o)
        })
    }

    public func createTlsInspectionPolicy(
      request: CreateTlsInspectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTlsInspectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createTlsInspectionPolicy(request: r, options: o)
        })
    }

    public func updateTlsInspectionPolicy(
      request: UpdateTlsInspectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateTlsInspectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateTlsInspectionPolicy(request: r, options: o)
        })
    }

    public func deleteTlsInspectionPolicy(
      request: DeleteTlsInspectionPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteTlsInspectionPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteTlsInspectionPolicy(request: r, options: o)
        })
    }

    public func listAuthzPolicies(
      request: ListAuthzPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListAuthzPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListAuthzPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.ListAuthzPoliciesResponse
          in
          return try await self.inner.listAuthzPolicies(request: r, options: o)
        })
    }

    public func getAuthzPolicy(
      request: GetAuthzPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.AuthzPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetAuthzPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudNetworkSecurityV1.AuthzPolicy
          in
          return try await self.inner.getAuthzPolicy(request: r, options: o)
        })
    }

    public func createAuthzPolicy(
      request: CreateAuthzPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateAuthzPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAuthzPolicy(request: r, options: o)
        })
    }

    public func updateAuthzPolicy(
      request: UpdateAuthzPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateAuthzPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAuthzPolicy(request: r, options: o)
        })
    }

    public func deleteAuthzPolicy(
      request: DeleteAuthzPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteAuthzPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAuthzPolicy(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
