// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Organization AddressGroup is created under organization. Requests against
/// Organization AddressGroup will use project from request credential for
/// activation/quota/visibility check.
///
/// @Snippet(path: "OrganizationAddressGroupServiceQuickstart")
public class OrganizationAddressGroupServiceClient: Clients.OrganizationAddressGroupServiceProtocol
{
  let inner: any Clients.OrganizationAddressGroupServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `OrganizationAddressGroupServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.OrganizationAddressGroupServiceStub =
      try Clients.OrganizationAddressGroupServiceTransport(options)
    inner = Clients.OrganizationAddressGroupServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.OrganizationAddressGroupServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists address groups in a given project and location.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_ListAddressGroups")
  public func listAddressGroups(
    request: ListAddressGroupsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkSecurityV1.ListAddressGroupsResponse {
    try await self.inner.listAddressGroups(request: request, options: options)
  }

  /// Lists address groups in a given project and location.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_ListAddressGroups")
  public func listAddressGroups(
    byItem: ListAddressGroupsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AddressGroup, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudNetworkSecurityV1.ListAddressGroupsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listAddressGroups(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_GetAddressGroup")
  public func getAddressGroup(
    request: GetAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkSecurityV1.AddressGroup {
    try await self.inner.getAddressGroup(request: request, options: options)
  }

  /// Creates a new address group in a given project and location.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_CreateAddressGroup")
  public func createAddressGroup(
    request: CreateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAddressGroup(request: request, options: options)
  }

  /// Creates a new address group in a given project and location.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_CreateAddressGroup")
  public func createAddressGroup(
    withPolling: CreateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      return try op._extractStatus(AddressGroup.self)
    }
    let rawOp = try await self.createAddressGroup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates parameters of an address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_UpdateAddressGroup")
  public func updateAddressGroup(
    request: UpdateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAddressGroup(request: request, options: options)
  }

  /// Updates parameters of an address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_UpdateAddressGroup")
  public func updateAddressGroup(
    withPolling: UpdateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      return try op._extractStatus(AddressGroup.self)
    }
    let rawOp = try await self.updateAddressGroup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Adds items to an address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_AddAddressGroupItems")
  public func addAddressGroupItems(
    request: AddAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.addAddressGroupItems(request: request, options: options)
  }

  /// Adds items to an address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_AddAddressGroupItems")
  public func addAddressGroupItems(
    withPolling: AddAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      return try op._extractStatus(AddressGroup.self)
    }
    let rawOp = try await self.addAddressGroupItems(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Removes items from an address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_RemoveAddressGroupItems")
  public func removeAddressGroupItems(
    request: RemoveAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.removeAddressGroupItems(request: request, options: options)
  }

  /// Removes items from an address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_RemoveAddressGroupItems")
  public func removeAddressGroupItems(
    withPolling: RemoveAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      return try op._extractStatus(AddressGroup.self)
    }
    let rawOp = try await self.removeAddressGroupItems(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Clones items from one address group to another.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_CloneAddressGroupItems")
  public func cloneAddressGroupItems(
    request: CloneAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.cloneAddressGroupItems(request: request, options: options)
  }

  /// Clones items from one address group to another.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_CloneAddressGroupItems")
  public func cloneAddressGroupItems(
    withPolling: CloneAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      return try op._extractStatus(AddressGroup.self)
    }
    let rawOp = try await self.cloneAddressGroupItems(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_DeleteAddressGroup")
  public func deleteAddressGroup(
    request: DeleteAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAddressGroup(request: request, options: options)
  }

  /// Deletes an address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_DeleteAddressGroup")
  public func deleteAddressGroup(
    withPolling: DeleteAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAddressGroup(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists references of an address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_ListAddressGroupReferences")
  public func listAddressGroupReferences(
    request: ListAddressGroupReferencesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkSecurityV1.ListAddressGroupReferencesResponse {
    try await self.inner.listAddressGroupReferences(request: request, options: options)
  }

  /// Lists references of an address group.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_ListAddressGroupReferences")
  public func listAddressGroupReferences(
    byItem: ListAddressGroupReferencesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<
    ListAddressGroupReferencesResponse.AddressGroupReference, Swift.Error
  > {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkSecurityV1.ListAddressGroupReferencesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAddressGroupReferences(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "OrganizationAddressGroupService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `OrganizationAddressGroupServiceClient`.
  ///
  /// To mock `OrganizationAddressGroupServiceClient` change your functions to receive
  /// `some OrganizationAddressGroupServiceProtocol` or `any OrganizationAddressGroupServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol OrganizationAddressGroupServiceProtocol {
    /// See `OrganizationAddressGroupServiceClient.listAddressGroups`.
    func listAddressGroups(request: ListAddressGroupsRequest) async throws
      -> GoogleCloudNetworkSecurityV1.ListAddressGroupsResponse

    /// See `OrganizationAddressGroupServiceClient.listAddressGroups`.
    func listAddressGroups(
      byItem: ListAddressGroupsRequest
    ) throws -> any AsyncSequence<AddressGroup, Swift.Error>

    /// See `OrganizationAddressGroupServiceClient.listAddressGroups`.
    func listAddressGroups(
      parent: Swift.String,
    ) throws -> any AsyncSequence<AddressGroup, Swift.Error>

    /// See `OrganizationAddressGroupServiceClient.getAddressGroup`.
    func getAddressGroup(request: GetAddressGroupRequest) async throws
      -> GoogleCloudNetworkSecurityV1.AddressGroup

    /// See `OrganizationAddressGroupServiceClient.getAddressGroup`.
    func getAddressGroup(
      name: Swift.String,
    ) async throws -> GoogleCloudNetworkSecurityV1.AddressGroup

    /// See `OrganizationAddressGroupServiceClient.createAddressGroup`.
    func createAddressGroup(request: CreateAddressGroupRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.createAddressGroup`.
    func createAddressGroup(withPolling: CreateAddressGroupRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.createAddressGroup`.
    func createAddressGroup(
      parent: Swift.String,
      addressGroup: AddressGroup?,
      addressGroupId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.updateAddressGroup`.
    func updateAddressGroup(request: UpdateAddressGroupRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.updateAddressGroup`.
    func updateAddressGroup(withPolling: UpdateAddressGroupRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.updateAddressGroup`.
    func updateAddressGroup(
      addressGroup: AddressGroup?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.addAddressGroupItems`.
    func addAddressGroupItems(request: AddAddressGroupItemsRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.addAddressGroupItems`.
    func addAddressGroupItems(withPolling: AddAddressGroupItemsRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.addAddressGroupItems`.
    func addAddressGroupItems(
      addressGroup: Swift.String,
      items: [Swift.String],
    ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.removeAddressGroupItems`.
    func removeAddressGroupItems(request: RemoveAddressGroupItemsRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.removeAddressGroupItems`.
    func removeAddressGroupItems(withPolling: RemoveAddressGroupItemsRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.removeAddressGroupItems`.
    func removeAddressGroupItems(
      addressGroup: Swift.String,
      items: [Swift.String],
    ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.cloneAddressGroupItems`.
    func cloneAddressGroupItems(request: CloneAddressGroupItemsRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.cloneAddressGroupItems`.
    func cloneAddressGroupItems(withPolling: CloneAddressGroupItemsRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.cloneAddressGroupItems`.
    func cloneAddressGroupItems(
      addressGroup: Swift.String,
      sourceAddressGroup: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.deleteAddressGroup`.
    func deleteAddressGroup(request: DeleteAddressGroupRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.deleteAddressGroup`.
    func deleteAddressGroup(withPolling: DeleteAddressGroupRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `OrganizationAddressGroupServiceClient.deleteAddressGroup`.
    func deleteAddressGroup(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `OrganizationAddressGroupServiceClient.listAddressGroupReferences`.
    func listAddressGroupReferences(request: ListAddressGroupReferencesRequest) async throws
      -> GoogleCloudNetworkSecurityV1.ListAddressGroupReferencesResponse

    /// See `OrganizationAddressGroupServiceClient.listAddressGroupReferences`.
    func listAddressGroupReferences(
      byItem: ListAddressGroupReferencesRequest
    ) throws -> any AsyncSequence<
      ListAddressGroupReferencesResponse.AddressGroupReference, Swift.Error
    >

    /// See `OrganizationAddressGroupServiceClient.listAddressGroupReferences`.
    func listAddressGroupReferences(
      addressGroup: Swift.String,
    ) throws -> any AsyncSequence<
      ListAddressGroupReferencesResponse.AddressGroupReference, Swift.Error
    >

    /// See `OrganizationAddressGroupServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `OrganizationAddressGroupServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `OrganizationAddressGroupServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `OrganizationAddressGroupServiceClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `OrganizationAddressGroupServiceClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `OrganizationAddressGroupServiceClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `OrganizationAddressGroupServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `OrganizationAddressGroupServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `OrganizationAddressGroupServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `OrganizationAddressGroupServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `OrganizationAddressGroupServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `OrganizationAddressGroupServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `OrganizationAddressGroupServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `OrganizationAddressGroupServiceClient.listAddressGroups`.
    func listAddressGroups(
      request: ListAddressGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListAddressGroupsResponse

    /// See `OrganizationAddressGroupServiceClient.listAddressGroups`.
    func listAddressGroups(
      byItem: ListAddressGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AddressGroup, Swift.Error>

    /// See `OrganizationAddressGroupServiceClient.getAddressGroup`.
    func getAddressGroup(
      request: GetAddressGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.AddressGroup

    /// See `OrganizationAddressGroupServiceClient.createAddressGroup`.
    func createAddressGroup(
      request: CreateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.createAddressGroup`.
    func createAddressGroup(
      withPolling: CreateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.updateAddressGroup`.
    func updateAddressGroup(
      request: UpdateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.updateAddressGroup`.
    func updateAddressGroup(
      withPolling: UpdateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.addAddressGroupItems`.
    func addAddressGroupItems(
      request: AddAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.addAddressGroupItems`.
    func addAddressGroupItems(
      withPolling: AddAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.removeAddressGroupItems`.
    func removeAddressGroupItems(
      request: RemoveAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.removeAddressGroupItems`.
    func removeAddressGroupItems(
      withPolling: RemoveAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.cloneAddressGroupItems`.
    func cloneAddressGroupItems(
      request: CloneAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.cloneAddressGroupItems`.
    func cloneAddressGroupItems(
      withPolling: CloneAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup>

    /// See `OrganizationAddressGroupServiceClient.deleteAddressGroup`.
    func deleteAddressGroup(
      request: DeleteAddressGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `OrganizationAddressGroupServiceClient.deleteAddressGroup`.
    func deleteAddressGroup(
      withPolling: DeleteAddressGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `OrganizationAddressGroupServiceClient.listAddressGroupReferences`.
    func listAddressGroupReferences(
      request: ListAddressGroupReferencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudNetworkSecurityV1.ListAddressGroupReferencesResponse

    /// See `OrganizationAddressGroupServiceClient.listAddressGroupReferences`.
    func listAddressGroupReferences(
      byItem: ListAddressGroupReferencesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<
      ListAddressGroupReferencesResponse.AddressGroupReference, Swift.Error
    >

    /// See `OrganizationAddressGroupServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `OrganizationAddressGroupServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `OrganizationAddressGroupServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `OrganizationAddressGroupServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `OrganizationAddressGroupServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `OrganizationAddressGroupServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `OrganizationAddressGroupServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `OrganizationAddressGroupServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `OrganizationAddressGroupServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `OrganizationAddressGroupServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.OrganizationAddressGroupServiceProtocol {
  public func listAddressGroups(request: ListAddressGroupsRequest) async throws
    -> GoogleCloudNetworkSecurityV1.ListAddressGroupsResponse
  {
    try await self.listAddressGroups(request: request, options: .init())
  }

  public func listAddressGroups(
    request: ListAddressGroupsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkSecurityV1.ListAddressGroupsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAddressGroups(
    byItem: ListAddressGroupsRequest
  ) throws -> any AsyncSequence<AddressGroup, Swift.Error> {
    try self.listAddressGroups(byItem: byItem, options: .init())
  }

  public func listAddressGroups(
    byItem: ListAddressGroupsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AddressGroup, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudNetworkSecurityV1.ListAddressGroupsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAddressGroups(
    parent: Swift.String,
  ) throws -> any AsyncSequence<AddressGroup, Swift.Error> {
    let request = ListAddressGroupsRequest().with {
      $0.parent = parent
    }
    return try self.listAddressGroups(byItem: request)
  }

  public func getAddressGroup(request: GetAddressGroupRequest) async throws
    -> GoogleCloudNetworkSecurityV1.AddressGroup
  {
    try await self.getAddressGroup(request: request, options: .init())
  }

  public func getAddressGroup(
    request: GetAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkSecurityV1.AddressGroup {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAddressGroup(
    name: Swift.String,
  ) async throws -> GoogleCloudNetworkSecurityV1.AddressGroup {
    let request = GetAddressGroupRequest().with {
      $0.name = name
    }
    return try await self.getAddressGroup(request: request)
  }

  public func createAddressGroup(request: CreateAddressGroupRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAddressGroup(request: request, options: .init())
  }

  public func createAddressGroup(
    request: CreateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createAddressGroup(withPolling: CreateAddressGroupRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AddressGroup>
  {
    try await self.createAddressGroup(withPolling: withPolling, options: .init())
  }

  public func createAddressGroup(
    withPolling: CreateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAddressGroup(
    parent: Swift.String,
    addressGroup: AddressGroup?,
    addressGroupId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let request = CreateAddressGroupRequest().with {
      $0.parent = parent
      $0.addressGroup = addressGroup
      $0.addressGroupId = addressGroupId
    }
    return try await self.createAddressGroup(withPolling: request)
  }

  public func updateAddressGroup(request: UpdateAddressGroupRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAddressGroup(request: request, options: .init())
  }

  public func updateAddressGroup(
    request: UpdateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateAddressGroup(withPolling: UpdateAddressGroupRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AddressGroup>
  {
    try await self.updateAddressGroup(withPolling: withPolling, options: .init())
  }

  public func updateAddressGroup(
    withPolling: UpdateAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateAddressGroup(
    addressGroup: AddressGroup?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let request = UpdateAddressGroupRequest().with {
      $0.addressGroup = addressGroup
      $0.updateMask = updateMask
    }
    return try await self.updateAddressGroup(withPolling: request)
  }

  public func addAddressGroupItems(request: AddAddressGroupItemsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.addAddressGroupItems(request: request, options: .init())
  }

  public func addAddressGroupItems(
    request: AddAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func addAddressGroupItems(withPolling: AddAddressGroupItemsRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AddressGroup>
  {
    try await self.addAddressGroupItems(withPolling: withPolling, options: .init())
  }

  public func addAddressGroupItems(
    withPolling: AddAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func addAddressGroupItems(
    addressGroup: Swift.String,
    items: [Swift.String],
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let request = AddAddressGroupItemsRequest().with {
      $0.addressGroup = addressGroup
      $0.items = items
    }
    return try await self.addAddressGroupItems(withPolling: request)
  }

  public func removeAddressGroupItems(request: RemoveAddressGroupItemsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.removeAddressGroupItems(request: request, options: .init())
  }

  public func removeAddressGroupItems(
    request: RemoveAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func removeAddressGroupItems(withPolling: RemoveAddressGroupItemsRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AddressGroup>
  {
    try await self.removeAddressGroupItems(withPolling: withPolling, options: .init())
  }

  public func removeAddressGroupItems(
    withPolling: RemoveAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func removeAddressGroupItems(
    addressGroup: Swift.String,
    items: [Swift.String],
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let request = RemoveAddressGroupItemsRequest().with {
      $0.addressGroup = addressGroup
      $0.items = items
    }
    return try await self.removeAddressGroupItems(withPolling: request)
  }

  public func cloneAddressGroupItems(request: CloneAddressGroupItemsRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.cloneAddressGroupItems(request: request, options: .init())
  }

  public func cloneAddressGroupItems(
    request: CloneAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cloneAddressGroupItems(withPolling: CloneAddressGroupItemsRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AddressGroup>
  {
    try await self.cloneAddressGroupItems(withPolling: withPolling, options: .init())
  }

  public func cloneAddressGroupItems(
    withPolling: CloneAddressGroupItemsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AddressGroup>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func cloneAddressGroupItems(
    addressGroup: Swift.String,
    sourceAddressGroup: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<AddressGroup> {
    let request = CloneAddressGroupItemsRequest().with {
      $0.addressGroup = addressGroup
      $0.sourceAddressGroup = sourceAddressGroup
    }
    return try await self.cloneAddressGroupItems(withPolling: request)
  }

  public func deleteAddressGroup(request: DeleteAddressGroupRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAddressGroup(request: request, options: .init())
  }

  public func deleteAddressGroup(
    request: DeleteAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteAddressGroup(withPolling: DeleteAddressGroupRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAddressGroup(withPolling: withPolling, options: .init())
  }

  public func deleteAddressGroup(
    withPolling: DeleteAddressGroupRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAddressGroup(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteAddressGroupRequest().with {
      $0.name = name
    }
    return try await self.deleteAddressGroup(withPolling: request)
  }

  public func listAddressGroupReferences(request: ListAddressGroupReferencesRequest) async throws
    -> GoogleCloudNetworkSecurityV1.ListAddressGroupReferencesResponse
  {
    try await self.listAddressGroupReferences(request: request, options: .init())
  }

  public func listAddressGroupReferences(
    request: ListAddressGroupReferencesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudNetworkSecurityV1.ListAddressGroupReferencesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAddressGroupReferences(
    byItem: ListAddressGroupReferencesRequest
  ) throws -> any AsyncSequence<
    ListAddressGroupReferencesResponse.AddressGroupReference, Swift.Error
  > {
    try self.listAddressGroupReferences(byItem: byItem, options: .init())
  }

  public func listAddressGroupReferences(
    byItem: ListAddressGroupReferencesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<
    ListAddressGroupReferencesResponse.AddressGroupReference, Swift.Error
  > {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudNetworkSecurityV1.ListAddressGroupReferencesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAddressGroupReferences(
    addressGroup: Swift.String,
  ) throws -> any AsyncSequence<
    ListAddressGroupReferencesResponse.AddressGroupReference, Swift.Error
  > {
    let request = ListAddressGroupReferencesRequest().with {
      $0.addressGroup = addressGroup
    }
    return try self.listAddressGroupReferences(byItem: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
