// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents a Secure Access Connect (SAC) realm resource.
///
/// A Secure Access Connect realm establishes a connection between your Google
/// Cloud project and an SSE service.
public struct SACRealm: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. Resource name, in the form
  /// `projects/{project}/locations/global/sacRealms/{sacRealm}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Timestamp when the realm was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Timestamp when the realm was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Optional list of labels applied to the resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Immutable. SSE service provider associated with the realm.
  public var securityService: SACRealm.SecurityService = SACRealm.SecurityService()

  /// Output only. Key to be shared with SSE service provider during pairing.
  public var pairingKey: SACRealm.PairingKey? = nil

  /// Output only. State of the realm.
  public var state: SACRealm.State = SACRealm.State()

  /// Initialize a new instance of `SACRealm`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SACRealm().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Key to be shared with SSE service provider to establish global handshake.
  public struct PairingKey: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. Key value.
    public var key: Swift.String = Swift.String()

    /// Output only. Timestamp in UTC of when this resource is considered
    /// expired. It expires 7 days after creation.
    public var expireTime: GoogleCloudWKT.Timestamp? = nil

    /// Initialize a new instance of `PairingKey`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PairingKey().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.networksecurity.v1.SACRealm.PairingKey"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// SSE service provider
  public enum SecurityService: Codable, Equatable, Sendable {
    /// The default value. This value is used if the state is omitted.
    case unspecified
    /// [Palo Alto Networks Prisma
    /// Access](https://www.paloaltonetworks.com/sase/access).
    case paloAltoPrismaAccess
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .paloAltoPrismaAccess: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SECURITY_SERVICE_UNSPECIFIED"
      case .paloAltoPrismaAccess: return "PALO_ALTO_PRISMA_ACCESS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SecurityService/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SECURITY_SERVICE_UNSPECIFIED": self = .unspecified
      case "PALO_ALTO_PRISMA_ACCESS": self = .paloAltoPrismaAccess
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SecurityService/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .paloAltoPrismaAccess
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .paloAltoPrismaAccess: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// State of the realm.
  public enum State: Codable, Equatable, Sendable {
    /// No state specified. This should not be used.
    case unspecified
    /// Currently attached to a partner.
    case partnerAttached
    /// Was once attached to a partner but has been detached.
    case partnerDetached
    /// Is not attached to a partner and has an expired pairing key.
    /// Used only for Prisma Access.
    case keyExpired
    /// Has never been attached to a partner.
    /// Used only for Prisma Access.
    case pendingPartnerAttachment
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .partnerAttached: return 1
      case .partnerDetached: return 2
      case .keyExpired: return 3
      case .pendingPartnerAttachment: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .partnerAttached: return "PARTNER_ATTACHED"
      case .partnerDetached: return "PARTNER_DETACHED"
      case .keyExpired: return "KEY_EXPIRED"
      case .pendingPartnerAttachment: return "PENDING_PARTNER_ATTACHMENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PENDING_PARTNER_ATTACHMENT": self = .pendingPartnerAttachment
      case "PARTNER_ATTACHED": self = .partnerAttached
      case "PARTNER_DETACHED": self = .partnerDetached
      case "KEY_EXPIRED": self = .keyExpired
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .partnerAttached
      case 2: self = .partnerDetached
      case 3: self = .keyExpired
      case 7: self = .pendingPartnerAttachment
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .partnerAttached: return try container.encode(1)
      case .partnerDetached: return try container.encode(2)
      case .keyExpired: return try container.encode(3)
      case .pendingPartnerAttachment: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networksecurity.v1.SACRealm"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
