// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// SecurityProfileGroup is a resource that defines the behavior for various
/// ProfileTypes.
public struct SecurityProfileGroup: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. Identifier. Name of the SecurityProfileGroup resource. It
  /// matches pattern
  /// `projects|organizations/*/locations/{location}/securityProfileGroups/{security_profile_group}`.
  public var name: Swift.String = Swift.String()

  /// Optional. An optional description of the profile group. Max length 2048
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Output only. Resource creation timestamp.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Last resource update timestamp.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. This checksum is computed by the server based on the value of
  /// other fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. Identifier used by the data-path. Unique within `{container,
  /// location}`.
  public var dataPathId: Swift.UInt64 = Swift.UInt64()

  /// Optional. Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Reference to a SecurityProfile with the ThreatPrevention
  /// configuration.
  public var threatPreventionProfile: Swift.String = Swift.String()

  /// Optional. Reference to a SecurityProfile with the CustomMirroring
  /// configuration.
  public var customMirroringProfile: Swift.String = Swift.String()

  /// Optional. Reference to a SecurityProfile with the CustomIntercept
  /// configuration.
  public var customInterceptProfile: Swift.String = Swift.String()

  /// Optional. Reference to a SecurityProfile with the UrlFiltering
  /// configuration.
  public var urlFilteringProfile: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SecurityProfileGroup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecurityProfileGroup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let etag = CodingKeys(stringValue: "etag")
    static let dataPathId = CodingKeys(stringValue: "dataPathId")
    static let labels = CodingKeys(stringValue: "labels")
    static let threatPreventionProfile = CodingKeys(stringValue: "threatPreventionProfile")
    static let customMirroringProfile = CodingKeys(stringValue: "customMirroringProfile")
    static let customInterceptProfile = CodingKeys(stringValue: "customInterceptProfile")
    static let urlFilteringProfile = CodingKeys(stringValue: "urlFilteringProfile")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "createTime",
      "updateTime",
      "etag",
      "dataPathId",
      "labels",
      "threatPreventionProfile",
      "customMirroringProfile",
      "customInterceptProfile",
      "urlFilteringProfile",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.UInt64.self, forKey: .dataPathId) {
      self.dataPathId = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .threatPreventionProfile)
    {
      self.threatPreventionProfile = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .customMirroringProfile)
    {
      self.customMirroringProfile = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .customInterceptProfile)
    {
      self.customInterceptProfile = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .urlFilteringProfile) {
      self.urlFilteringProfile = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.dataPathId, forKey: .dataPathId)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.threatPreventionProfile, forKey: .threatPreventionProfile)
    try container.encode(self.customMirroringProfile, forKey: .customMirroringProfile)
    try container.encode(self.customInterceptProfile, forKey: .customInterceptProfile)
    try container.encode(self.urlFilteringProfile, forKey: .urlFilteringProfile)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networksecurity.v1.SecurityProfileGroup"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
