// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// SecurityProfileGroup is a resource that defines the behavior for various
/// ProfileTypes.
public struct SecurityProfileGroup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. Identifier. Name of the SecurityProfileGroup resource. It
  /// matches pattern
  /// `projects|organizations/*/locations/{location}/securityProfileGroups/{security_profile_group}`.
  public var name: Swift.String = Swift.String()

  /// Optional. An optional description of the profile group. Max length 2048
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Output only. Resource creation timestamp.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Last resource update timestamp.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. This checksum is computed by the server based on the value of
  /// other fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Output only. Identifier used by the data-path. Unique within `{container,
  /// location}`.
  public var dataPathId: Swift.UInt64 = Swift.UInt64()

  /// Optional. Labels as key value pairs.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Reference to a SecurityProfile with the ThreatPrevention
  /// configuration.
  public var threatPreventionProfile: Swift.String = Swift.String()

  /// Optional. Reference to a SecurityProfile with the CustomMirroring
  /// configuration.
  public var customMirroringProfile: Swift.String = Swift.String()

  /// Optional. Reference to a SecurityProfile with the CustomIntercept
  /// configuration.
  public var customInterceptProfile: Swift.String = Swift.String()

  /// Optional. Reference to a SecurityProfile with the UrlFiltering
  /// configuration.
  public var urlFilteringProfile: Swift.String = Swift.String()

  /// Initialize a new instance of `SecurityProfileGroup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecurityProfileGroup().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networksecurity.v1.SecurityProfileGroup"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
