// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Specification of ValidationCA. Defines the mechanism to obtain the
/// Certificate Authority certificate to validate the peer certificate.
public struct ValidationCA: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The type of certificate provider which provides the CA certificate.
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `ValidationCA`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ValidationCA().with { $0.grpcEndpoint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case grpcEndpoint = "grpcEndpoint"
    case certificateProviderInstance = "certificateProviderInstance"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let grpcEndpoint = try container.decodeIfPresent(GrpcEndpoint?.self, forKey: .grpcEndpoint) {
      try typeCheckAndSet(.grpcEndpoint(grpcEndpoint))
    }
    if let certificateProviderInstance = try container.decodeIfPresent(
      CertificateProviderInstance?.self, forKey: .certificateProviderInstance)
    {
      try typeCheckAndSet(.certificateProviderInstance(certificateProviderInstance))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.type {
      switch choice {
      case .grpcEndpoint(let value):
        try container.encode(value, forKey: .grpcEndpoint)
      case .certificateProviderInstance(let value):
        try container.encode(value, forKey: .certificateProviderInstance)
      }
    }
  }

  /// The type of certificate provider which provides the CA certificate.
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// gRPC specific configuration to access the gRPC server to
    /// obtain the CA certificate.
    indirect case grpcEndpoint(GrpcEndpoint?)
    /// The certificate provider instance specification that will be passed to
    /// the data plane, which will be used to load necessary credential
    /// information.
    indirect case certificateProviderInstance(CertificateProviderInstance?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.networksecurity.v1.ValidationCA"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
